version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  run-pytest-bdd-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - python/install-packages:
          pkg-manager: poetry

workflows:
  pytest-bdd-workflow:
    jobs:
      - run-pytest-bdd-job
