# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  install-poetry:
    steps:
      - run:
          name: "Install the latest poetry"
          command: |
              if [ "$(which pip3)" = "/usr/local/bin/pip3" ]; then
                  sudo pip3 install poetry
              else
                  pip3 install poetry
              fi

  install-packages:
    steps:
      - run:
          name: "Install the packages"
          command: poetry install

jobs:
  run-pytest-bdd-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - install-poetry
      - install-packages


workflows:
  pytest-bdd-workflow:
    jobs:
      - run-pytest-bdd-job
 

